services:

  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: server --tls-san "kubectl"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=${K3S_TOKEN:?err}
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    - .:/output
    ports:
    - 6443:6443
    - 80:80
    - 443:443
    networks:
      - k3s

  agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=${K3S_TOKEN:?err}
    networks:
      - k3s

  kubectl:
    image: kubectl:latest
    depends_on:
      - server
    environment:
      - K3S_URL=https://server:6443
    volumes:
      - .:/output
    networks:
      - k3s

volumes:
  k3s-server: {}
  k3s-config: {}

networks:
  k3s:
    driver: bridge
