services:

  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: server --tls-san "kubectl"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=${K3S_TOKEN:-secret}
    - K3S_KUBECONFIG_OUTPUT=/output/config
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    - .:/output
    ports:
    - 80:80
    - 443:443
    networks:
      - k3s

  agent-1:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=${K3S_TOKEN:-secret}
    networks:
      - k3s

  agent-2:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=${K3S_TOKEN:-secret}
    networks:
      - k3s

  kubectl:
    image: sysperu/kubectl:latest
    # image: kubectl:latest
    depends_on:
      - server
    environment:
      - K3S_URL=https://server:6443
      - RANCHER_ADMIN_PASSWORD=${RANCHER_ADMIN_PASSWORD:-admin}
      - RANCHER_DOMAIN=${RANCHER_DOMAIN:-rancher.local}
    volumes:
      - .:/output
    networks:
      - k3s

volumes:
  k3s-server: {}
  k3s-config: {}

networks:
  k3s:
    driver: bridge